### ISSUE TITLE
patterns crashes on 950arnold

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#147]
BleepBloop
Blooms
Bloop
CounterSpin
Growth
Lightning
PartyRings
Pixels
Radar
SparkleHelix
SparkleTakeover
SparkleWave
Sparks
Twinkle
UpNDown

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at entwined.pattern.colin_hunt.BleepBloop.bufferedRun(BleepBloop.java:47)
	at entwined.core.TSBufferedPattern.run(TSBufferedPattern.java:19)
	at heronarts.lx.pattern.LXPattern.onLoop(LXPattern.java:363)
	at heronarts.lx.LXLayeredComponent.loop(LXLayeredComponent.java:104)
	at heronarts.lx.LXDeviceComponent.loop(LXDeviceComponent.java:250)
	at heronarts.lx.mixer.LXChannel.loop(LXChannel.java:1028)
	at heronarts.lx.mixer.LXMixerEngine.loop(LXMixerEngine.java:924)
	at heronarts.lx.LXEngine._run(LXEngine.java:1073)
	at heronarts.lx.LXEngine.run(LXEngine.java:946)
	at heronarts.lx.LXEngine.access$9(LXEngine.java:941)
	at heronarts.lx.LXEngine$ExecutorService.runLoop(LXEngine.java:692)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by bbulkow** [comment]
Needed to restart after changing fixtures.
