### ISSUE TITLE
FirefliesNCase crashes on 950arnold

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#148]
java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "java.util.Map.get(Object)" is null
	at entwined.pattern.evy.FirefliesNcase.bufferedRun(FirefliesNcase.java:77)
	at entwined.core.TSBufferedPattern.run(TSBufferedPattern.java:19)
	at heronarts.lx.pattern.LXPattern.onLoop(LXPattern.java:363)
	at heronarts.lx.LXLayeredComponent.loop(LXLayeredComponent.java:104)
	at heronarts.lx.LXDeviceComponent.loop(LXDeviceComponent.java:250)
	at heronarts.lx.mixer.LXChannel.loop(LXChannel.java:1028)
	at heronarts.lx.mixer.LXMixerEngine.loop(LXMixerEngine.java:924)
	at heronarts.lx.LXEngine._run(LXEngine.java:1073)
	at heronarts.lx.LXEngine.run(LXEngine.java:946)
	at heronarts.lx.LXEngine.access$9(LXEngine.java:941)
	at heronarts.lx.LXEngine$ExecutorService.runLoop(LXEngine.java:692)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by bbulkow** [comment]
This had to do with not reloading after a fixtures change.
