### ISSUE TITLE
Spiral Arms not loading

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#149]
heronarts.lx.LX$InstantiationException: SpiralArms could not be loaded. Check that all required content files are present and constructor is public.
	at heronarts.lx.LX.instantiateComponent(LX.java:1164)
	at heronarts.lx.LX.instantiateComponent(LX.java:1144)
	at heronarts.lx.LX.instantiatePattern(LX.java:1185)
	at heronarts.lx.mixer.LXChannel.loadPattern(LXChannel.java:1131)
	at heronarts.lx.mixer.LXChannel.load(LXChannel.java:1104)
	at heronarts.lx.mixer.LXMixerEngine.loadChannel(LXMixerEngine.java:1123)
	at heronarts.lx.mixer.LXMixerEngine.loadChannel(LXMixerEngine.java:1109)
	at heronarts.lx.mixer.LXMixerEngine.load(LXMixerEngine.java:1072)
	at heronarts.lx.LXComponent.load(LXComponent.java:1273)
	at heronarts.lx.LXEngine.load(LXEngine.java:1280)
	at heronarts.lx.LX.openProject(LX.java:960)
	at heronarts.lx.LXPreferences.loadInitialProject(LXPreferences.java:304)
	at heronarts.lx.studio.Chromatik.lambda$0(Chromatik.java:271)
	at heronarts.lx.LXEngine._run(LXEngine.java:1041)
	at heronarts.lx.LXEngine.run(LXEngine.java:946)
	at heronarts.lx.LXEngine.access$9(LXEngine.java:941)
	at heronarts.lx.LXEngine$ExecutorService.runLoop(LXEngine.java:692)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at heronarts.lx.LX.instantiateComponent(LX.java:1158)
	... 22 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1347)
	at entwined.pattern.adam_n_katie.SpiralArms.<init>(SpiralArms.java:48)
	... 28 more

**Comment by bbulkow** [comment]
This was throwing an exception when there was no center object. Seemed to be coded defensively,
but there was a getter. Surround with a try block and all is good.
