### ISSUE TITLE
Strange Crash On Exit

### ISSUE THREAD

**Issue by meawoppl** [squaredproject/Entwined#18]
About 1 in 3 times I see this on exiting:
```
> Task :compileJava
Note: /home/meawoppl/repos/Entwined/src/main/java/com/charlesgadeken/entwined/effects/original/ColorEffect.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :run
[LX 2020/11/25 20:29:34] Initializing LX version 0.2.1
[LX 2020/11/25 20:29:40] LXEngine Core Thread starting.
[LX 2020/11/25 20:30:30] FATAL TOP-LEVEL EXCEPTION IN ENGINE: null
java.util.ConcurrentModificationException
[LX 2020/11/25 20:30:30] [MIDI] LXMidiEngine Device Update Thread finished.
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
        at java.util.ArrayList$Itr.next(ArrayList.java:861)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044)
        at heronarts.lx.mixer.LXMixerEngine.loop(LXMixerEngine.java:886)
        at heronarts.lx.LXEngine._run(LXEngine.java:854)
        at heronarts.lx.LXEngine.run(LXEngine.java:750)
        at heronarts.lx.LXEngine.access$900(LXEngine.java:59)
        at heronarts.lx.LXEngine$EngineThread$RenderTask.run(LXEngine.java:622)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
```

**Comment by meawoppl** [comment]
Maybe related:
```
LX 2020/12/01 14:23:55] FATAL TOP-LEVEL EXCEPTION IN ENGINE: null
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
        at java.util.ArrayList$Itr.next(ArrayList.java:861)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044)
        at heronarts.lx.mixer.LXMixerEngine.loop(LXMixerEngine.java:886)
        at heronarts.lx.LXEngine._run(LXEngine.java:854)
        at heronarts.lx.LXEngine.run(LXEngine.java:750)
        at heronarts.lx.LXEngine.access$900(LXEngine.java:59)
        at heronarts.lx.LXEngine$EngineThread$RenderTask.run(LXEngine.java:622)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
[LX 2020/12/01 14:23:56] Stranded listener on parameter: /lx/mixer/channel/8/fader - com.charlesgadeken.entwined.EntwinedGui$$Lambda$92/188782082
java.lang.Exception
        at heronarts.lx.parameter.LXListenableParameter.dispose(LXListenableParameter.java:156)
        at heronarts.lx.LXComponent.removeParameter(LXComponent.java:928)
        at heronarts.lx.LXComponent.dispose(LXComponent.java:809)
        at heronarts.lx.LXModulatorComponent.dispose(LXModulatorComponent.java:137)
        at heronarts.lx.mixer.LXBus.dispose(LXBus.java:412)
        at heronarts.lx.mixer.LXAbstractChannel.dispose(LXAbstractChannel.java:341)
        at heronarts.lx.mixer.LXChannel.dispose(LXChannel.java:905)
        at heronarts.lx.mixer.LXMixerEngine.removeChannel(LXMixerEngine.java:698)
        at heronarts.lx.mixer.LXMixerEngine.dispose(LXMixerEngine.java:1032)
        at heronarts.lx.LXEngine.dispose(LXEngine.java:1049)
        at heronarts.lx.LX.dispose(LX.java:550)
        at heronarts.p3lx.P3LX.dispose(P3LX.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1436)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1429)
        at processing.core.PApplet.handleMethods(PApplet.java:1628)
        at processing.core.PApplet.dispose(PApplet.java:3837)
        at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:880)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
        at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
        at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by bbulkow** [comment]
This is on the previous port to LX which is now defunct. Closing, won'tfix
