### ISSUE TITLE
Occasional Startup Issue

### ISSUE THREAD

**Issue by meawoppl** [squaredproject/Entwined#22]
```
setup() completed
handleDraw() called before finishing
com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread main-FPSAWTAnimator#00-Timer0
        at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
        at com.jogamp.newt.opengl.GLWindow.access$200(GLWindow.java:119)
        at com.jogamp.newt.opengl.GLWindow$2.windowResized(GLWindow.java:141)
        at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4383)
        at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:4317)
        at jogamp.newt.WindowImpl.sizeChanged(WindowImpl.java:4520)
        at jogamp.newt.WindowImpl.sizePosMaxInsetsVisibleChanged(WindowImpl.java:4864)
        at jogamp.newt.driver.x11.DisplayDriver.DispatchMessages0(Native Method)
        at jogamp.newt.driver.x11.DisplayDriver.dispatchMessagesNative(DisplayDriver.java:112)
        at jogamp.newt.WindowImpl.waitForSize(WindowImpl.java:4534)
        at jogamp.newt.WindowImpl.access$600(WindowImpl.java:96)
        at jogamp.newt.WindowImpl$SetSizeAction.run(WindowImpl.java:1369)
        at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2780)
        at jogamp.newt.WindowImpl.setSize(WindowImpl.java:1394)
        at com.jogamp.newt.opengl.GLWindow.setSize(GLWindow.java:588)
        at processing.opengl.PSurfaceJOGL.setSize(PSurfaceJOGL.java:770)
        at heronarts.p3lx.ui.UI.pre(UI.java:832)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1436)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1429)
        at processing.core.PApplet.handleMethods(PApplet.java:1628)
        at processing.core.PApplet.handleDraw(PApplet.java:2473)
        at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
        at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
        at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ThreadDeath
        at java.lang.Thread.stop(Thread.java:853)
        at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:724)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:719)
        at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:635)
        at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:123)
        at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:74)
        at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:274)
        at com.jogamp.nativewindow.NativeWindowFactory$2$1.run(NativeWindowFactory.java:192)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by meawoppl** [comment]
Got another instance of it:
```
LX 2020/12/01 14:23:55] FATAL TOP-LEVEL EXCEPTION IN ENGINE: null
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
        at java.util.ArrayList$Itr.next(ArrayList.java:861)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1044)
        at heronarts.lx.mixer.LXMixerEngine.loop(LXMixerEngine.java:886)
        at heronarts.lx.LXEngine._run(LXEngine.java:854)
        at heronarts.lx.LXEngine.run(LXEngine.java:750)
        at heronarts.lx.LXEngine.access$900(LXEngine.java:59)
        at heronarts.lx.LXEngine$EngineThread$RenderTask.run(LXEngine.java:622)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
[LX 2020/12/01 14:23:56] Stranded listener on parameter: /lx/mixer/channel/8/fader - com.charlesgadeken.entwined.EntwinedGui$$Lambda$92/188782082
java.lang.Exception
        at heronarts.lx.parameter.LXListenableParameter.dispose(LXListenableParameter.java:156)
        at heronarts.lx.LXComponent.removeParameter(LXComponent.java:928)
        at heronarts.lx.LXComponent.dispose(LXComponent.java:809)
        at heronarts.lx.LXModulatorComponent.dispose(LXModulatorComponent.java:137)
        at heronarts.lx.mixer.LXBus.dispose(LXBus.java:412)
        at heronarts.lx.mixer.LXAbstractChannel.dispose(LXAbstractChannel.java:341)
        at heronarts.lx.mixer.LXChannel.dispose(LXChannel.java:905)
        at heronarts.lx.mixer.LXMixerEngine.removeChannel(LXMixerEngine.java:698)
        at heronarts.lx.mixer.LXMixerEngine.dispose(LXMixerEngine.java:1032)
        at heronarts.lx.LXEngine.dispose(LXEngine.java:1049)
        at heronarts.lx.LX.dispose(LX.java:550)
        at heronarts.p3lx.P3LX.dispose(P3LX.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1436)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1429)
        at processing.core.PApplet.handleMethods(PApplet.java:1628)
        at processing.core.PApplet.dispose(PApplet.java:3837)
        at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:880)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
        at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
        at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by bbulkow** [comment]
THis is on the old version of the LXport. Closing, will not fix.
