### ISSUE TITLE
Explosions Pattern is Crashy

### ISSUE THREAD

**Issue by meawoppl** [squaredproject/Entwined#29]
```
[LX 2020/12/01 17:46:32] Unexpected exception in device loop com.charlesgadeken.entwined.patterns.contributors.kyleFleming.Explosions: null
java.lang.NullPointerException
        at com.charlesgadeken.entwined.patterns.contributors.kyleFleming.VecUtils.movePointToSamePlane(VecUtils.java:20)
        at com.charlesgadeken.entwined.patterns.contributors.kyleFleming.Explosion.getBrightnessForCube(Explosion.java:77)
        at com.charlesgadeken.entwined.patterns.contributors.kyleFleming.MultiObject.getColorForCube(MultiObject.java:64)
        at com.charlesgadeken.entwined.patterns.contributors.kyleFleming.Explosion.getColorForCube(Explosion.java:12)
        at com.charlesgadeken.entwined.patterns.contributors.kyleFleming.MultiObject.run(MultiObject.java:39)
        at com.charlesgadeken.entwined.patterns.contributors.kyleFleming.Explosion.run(Explosion.java:12)
        at heronarts.lx.LXLayer.onLoop(LXLayer.java:44)
        at heronarts.lx.LXLayeredComponent.loop(LXLayeredComponent.java:119)
        at heronarts.lx.LXLayeredComponent.loop(LXLayeredComponent.java:127)
        at heronarts.lx.LXDeviceComponent.loop(LXDeviceComponent.java:146)
        at heronarts.lx.mixer.LXChannel.loop(LXChannel.java:849)
        at heronarts.lx.mixer.LXMixerEngine.loop(LXMixerEngine.java:887)
        at heronarts.lx.LXEngine._run(LXEngine.java:854)
        at heronarts.lx.LXEngine.run(LXEngine.java:750)
        at heronarts.lx.LXEngine.access$900(LXEngine.java:59)
        at heronarts.lx.LXEngine$EngineThread$RenderTask.run(LXEngine.java:622)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
NoteOff
```

@kylefleming maybe?

**Comment by bbulkow** [comment]
Many of these patterns were crashy because they were not using the correct classes - they were using a length of all the "bulbs" but were only looking in the Cubes data structure. The 'oldlx' versions have been updated and are now stable.

**Comment by bbulkow** [comment]
This is the old version of newlx, closing, will not fix
